### ISSUE TITLE
doesnt appear in server list

### ISSUE THREAD

**Issue by arceuss** [jpenilla/MiniMOTD-Fabric#2]
motd-enabled is set to true but it doesnt work
![image](https://user-images.githubusercontent.com/28229451/96799221-dcdbb680-13bf-11eb-8c77-50d9e1e84032.png)
it has the fake player stuff but not the motd

**Comment by jpenilla** [comment]
cant reproduce. join my discord for support https://discord.gg/YxZMfJ
